spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: supercatstore3@gmail.com
    password: ihmhzylweobbapzc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분


  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true

  config:
    import:
      - classpath:mysql.yml

springdoc:
  swagger-ui:
    path: /api-doc.html

