spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true

  config:
    import:
      - classpath:mysql.yml
